/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        alexa: ["ALEXA", "sans-serif"],
        amanda: ["AMANDA", "sans-serif"],
        amsterdam: ["AMSTERDAM", "sans-serif"],
        austin: ["AUSTIN", "sans-serif"],
        avante: ["AVANTE", "sans-serif"],
        barcelone: ["BARCELONA", "sans-serif"],
        bayview: ["BAYVIEW", "sans-serif"],
        beachfront: ["BEACHFRONT", "sans-serif"],
        buttercup: ["BUTTERCUP", "sans-serif"],
        chelsea: ["CHELSEA", "sans-serif"],
        classicType: ["CLASSICTYPE", "sans-serif"],
        freehand: ["FREEHAND", "sans-serif"],
        freespirit: ["FREESPIRIT", "sans-serif"],
        greenworld: ["GREENWORLD", "sans-serif"],
        loveneon: ["LOVENEON", "sans-serif"],
        monaco: ["MONACO", "sans-serif"],
        neonscript: ["NEONSCRIPT", "sans-serif"],
        neotokyo: ["NEOTOKYO", "sans-serif"],
        newcursive: ["NEWCURSIVE", "sans-serif"],
        northshore: ["NORTHSHORE", "sans-serif"],
        photogenic: ["PHOTOGENIC", "sans-serif"],
        rocket: ["ROCKET", "sans-serif"],
        royalty: ["ROYALTY", "sans-serif"],
        sciFI: ["SCIFI", "sans-serif"],
        signature: ["SIGNATURE", "sans-serif"],
        sorrento: ["SORRENTO", "sans-serif"],
        venetian: ["VENETIAN", "sans-serif"],
        vintage: ["VINTAGE", "sans-serif"],
        waikiki: ["WAIKIKI", "sans-serif"],
      },
    },
    colors: {
      transparent: "transparent",
      white: "#ffffff",
      black: "#000000",
      pink: "#FF00B4",
      yellow: "#ffe800",
    },
  },
  plugins: [],
};
